
apiVersion: batch/v1
kind: CronJob
metadata:
  name: gp-engine-pre-process
spec:
  schedule: "@hourly"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gp-engine-pre-process
            image: node:latest
            imagePullPolicy: IfNotPresent
            command:
              - /bin/sh
            args:
              - -c
              - | 
                git clone https://github.com/djw8605/gp-engine-dash.git /opt/gp-engine-dash &&
                cd /opt/gp-engine-dash &&
                npm i &&
                npx tsc --resolveJsonModule --esModuleInterop pre-parse/*.ts &&
                node pre-parse/main.js
            env:
              - name: NAUTILUS_ID
                valueFrom:
                  secretKeyRef:
                    name: nautilus-secret
                    key: NAUTILUS_ID
              - name: NAUTILUS_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: nautilus-secret
                    key: NAUTILUS_ACCESS_KEY
            resources:
              requests:
                cpu: "1"
                memory: 4Gi
              limits:
                cpu: "1"
                memory: 4Gi
          restartPolicy: OnFailure






